In [2]:
import STARTHER
import nvdbapi
import pandas as pd

# Plan fremover (mandag 29.10)

  * [ ] Hent ut vegnett-tilknytning for alle disse 563 objektene
  * [ ] Hent ut reflinkpart med startdato < idag for den ROUTE_ID som hører til. 
  * [ ] Få opp i kart / lag datadump som Paul kan se på

In [5]:
fn = '../data/487-eksportHELEnorge2018okt27.csv'

hlp = pd.read_csv(fn, sep=';', encoding='iso-8859-1')

/home/jan/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (14,15,17,18,44,48,49,57) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [25]:
len( hlp[hlp.stedfesting.isna()])

563

In [29]:
hlp[ hlp.stedfesting.isna()]['vegobjektid'].to_csv( 'vegobjektid_ugyldigveg.csv', index=False)

In [14]:
hlp[ hlp.stedfesting.isna() & (~hlp['Geometri, linje'].isna() | ~hlp['Geometri, punkt'].isna())][[ 'vegobjektid', 'startdato', 'sistmodifisert', 'Geometri, linje', 'Geometri, punkt']]

,vegobjektid,startdato,sistmodifisert,"Geometri, linje","Geometri, punkt"
9120,84440290,2014-01-08,2014-02-27T14:52:02,MULTILINESTRING ((79958.2600097656 6513866.809...,NaN
15790,89580580,2012-09-03,2015-07-08T12:07:47,NaN,POINT (581320.039555609 7602807.14042809 9.909)
40449,579113222,2015-01-14,2016-02-22T12:53:35,"MULTILINESTRING ((198645.61 6867013.8 364.63, ...",NaN
47056,599414847,2015-06-05,2015-10-16T15:40:38,"MULTILINESTRING ((206172.84 6695863.43 152.97,...",NaN
47218,616231968,2015-08-05,2015-08-05T10:06:25,NaN,POINT (336354.36631421 6723544.23782938 0)
47404,634631997,2015-09-21,2015-11-12T14:56:53,"MULTILINESTRING ((210009.68 6677658.53 140.47,...",NaN
47533,641895771,2015-08-15,2016-04-19T13:52:13,NaN,POINT (252668.110303584 6706625.30971236 0)
47535,641895773,2015-08-15,2016-04-19T13:52:13,NaN,POINT (252652.877776995 6706638.76858859 0)
47614,645177299,2015-11-13,2016-03-17T08:46:23,"MULTILINESTRING ((87470.82 6466638.42 8.98, 87...",NaN
47615,645177333,2015-11-13,2016-03-17T08:46:23,"MULTILINESTRING ((87127.87 6466825.35 9.03, 87...",NaN

In [16]:
ughlp = hlp[ hlp.stedfesting.isna()].copy()
len(ughlp)

563

In [20]:
ughlp[ ~ughlp['Geometri, linje'].isna()].to_csv( '../data/hlp_ugyldigvegnett_egengeom_linje.csv', 
                                                    sep=';', encoding='utf-8', quoting=1)

In [21]:
ughlp[ ~ughlp['Geometri, punkt'].isna()].to_csv( '../data/hlp_ugyldigvegnett_egengeom_punkt.csv', 
                                                    sep=';', encoding='utf-8', quoting=1)

In [18]:
egengeom = ughlp[ ~ughlp['Geometri, linje'].isna() | ~ughlp['Geometri, punkt'].isna() ]
egengeom

,vegobjektid,type_id,versjonid,startdato,sistmodifisert,UU_Type transportmiddel,UU_Type,UU_Viktighetsnivå,UU_På- og avstigning,"Trafikkretning, geografisk",...,vegkategori,vegstatus,vegnummer,fra hp,til hp,fra meter,til meter,stedfesting,geometri,srid
9120,84440290,487,4,2014-01-08,2014-02-27T14:52:02,NaN,Plattform og lomme,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15790,89580580,487,2,2012-09-03,2015-07-08T12:07:47,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40449,579113222,487,1,2015-01-14,2016-02-22T12:53:35,NaN,Kantstopp,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47056,599414847,487,1,2015-06-05,2015-10-16T15:40:38,NaN,Kantstopp,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47218,616231968,487,2,2015-08-05,2015-08-05T10:06:25,Buss,Kantstopp,Regionalt knutepunkt,Både på- og avstigning,Begge,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47404,634631997,487,1,2015-09-21,2015-11-12T14:56:53,NaN,Plattform og lomme,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47533,641895771,487,1,2015-08-15,2016-04-19T13:52:13,NaN,Annen type,Lokalt knutepunkt,Både på- og avstigning,Varierer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47535,641895773,487,1,2015-08-15,2016-04-19T13:52:13,NaN,Annen type,Regionalt knutepunkt,Både på- og avstigning,Varierer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47614,645177299,487,1,2015-11-13,2016-03-17T08:46:23,NaN,Plattform og lomme,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47615,645177333,487,1,2015-11-13,2016-03-17T08:46:23,NaN,Plattform og lomme,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
egengeom.to_csv(  '../data/hlp_ugyldigvegnett_egengeom.csv', sep=';', encoding='utf-8', quoting=1)

In [24]:
len( ughlp[ ~ughlp['Geometri, punkt'].isna() ] )

4